name: CI & Pack DfE.CoreLibs.TestPackage

on:
  push:
    branches: [ main ]
    paths:
      - 'src/DfE.CoreLibs.TestPackage/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/DfE.CoreLibs.TestPackage/**'

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test-template.yml
    with:
      project_name: DfE.CoreLibs.TestPackage
      project_path: src/DfE.CoreLibs.TestPackage
      run_tests: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pack-and-release:
    needs: build-and-test
    if: needs.build-and-test.result == 'success'
    uses: ./.github/workflows/pack-template.yml
    with:
      project_name: DfE.CoreLibs.TestPackage
      project_path: src/DfE.CoreLibs.TestPackage/DfE.CoreLibs.TestPackage.csproj
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}