name: CI & Pack GovUK.Dfe.CoreLibs.FileStorage

on:
  push:
    branches: [ main ]
    paths:
      - "src/GovUK.Dfe.CoreLibs.FileStorage/**"
  pull_request:
    branches: [ main ]
    paths:
      - "src/GovUK.Dfe.CoreLibs.FileStorage/**"

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test-template.yml
    with:
      project_name: GovUK.Dfe.CoreLibs.FileStorage
      project_path: src/GovUK.Dfe.CoreLibs.FileStorage
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pack-and-release:
    needs: build-and-test
    if: needs.build-and-test.result == 'success'
    uses: ./.github/workflows/pack-template.yml
    with:
      project_name: GovUK.Dfe.CoreLibs.FileStorage
      project_path: src/GovUK.Dfe.CoreLibs.FileStorage/GovUK.Dfe.CoreLibs.FileStorage.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
