name: Build DfE.CoreLibs.Security

on:
  push:
    branches:
      - main
    paths:
      - 'src/DfE.CoreLibs.Security/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/DfE.CoreLibs.Security/**' 

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test-template.yml
    with:
      project_name: DfE.CoreLibs.Security
      project_path: src/DfE.CoreLibs.Security
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}