name: Pack DfE.CoreLibs.Http

on:
  workflow_run:
    workflows: ["Build DfE.CoreLibs.Http"]
    types:
      - completed

jobs:
  build-and-package:
    if: >
        github.event.workflow_run.conclusion == 'success' &&
        (
        (github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.event == 'push') ||
        github.event.workflow_run.event == 'pull_request'
        )   
    uses: ./.github/workflows/nuget-package-template.yml
    with:
      project_name: DfE.CoreLibs.Http
      project_path: src/DfE.CoreLibs.Http
      nuget_package_name: DfE.CoreLibs.Http
      custom_suffix: ${{ github.event.workflow_run.event == 'pull_request' && '-staging' || '' }}
