name: Pack DfE.CoreLibs.Utilities

on:
  workflow_run:
    workflows: ["Build DfE.CoreLibs.Utilities"]
    types:
      - completed
    branches:
      - main
    events:
      - push

jobs:
  build-and-package:
    uses: ./.github/workflows/nuget-package-template.yml
    with:
      project_name: DfE.CoreLibs.Utilities
      project_path: src/DfE.CoreLibs.Utilities
      nuget_package_name: DfE.CoreLibs.Utilities
